### ISSUE TITLE
No environment variable set for PHP?

### ISSUE THREAD

**Issue by yongzhihuang** [nlzet/docker-lemp-stack#3]
Hey there,

I got everything up and running, however when I look at the output of phpinfo(); I only see `USER` and `HOME` being listed under Environment variables.

The compose file specified the following env variables:

```
    PHP_ENV: 'development'
    PHP_APCU_ENABLED: 'false'
    PHP_XDEBUG_ENABLED: 'true'
    PHP_MAILCATCHER_ENABLED: 'true'
```

I was wondering if you know why they're not listed there, or am I looking at the wrong place?

Thank you! Great repo!

**Comment by nlzet** [comment]
Hi, i'm sorry I missed this issue, didn't see any notification.

The environment variables that are available via docker-compose are being processed when the container is launched. This means these aren't really PHP environment variables. See https://github.com/nlzet/docker-lemp-stack/blob/master/php70/my_init.d/02-setup-xdebug.sh#L8 for example.
