### ISSUE TITLE
gearman

### ISSUE THREAD

**Issue by imKota** [nlzet/docker-lemp-stack#6]
Please add support Gearman Job Server. http://gearman.org/
Since all attempts to install failed :(

**Comment by nlzet** [comment]
Gearman doesn't seem to fit in a basic lemp setup. If you want you can fork the repository to add your needs, or you can create a custom Dockerfile to add custom functionality.

Can you provide some information about what you tried and didn't work, maybe I can help you into the right direction.

**Comment by imKota** [comment]
closed
